### ISSUE TITLE
training porblem?

### ISSUE THREAD

**Issue by Wanghc233** [nv-tlabs/LION#58]

**Comment by Wanghc233** [comment]
Thank you for your amazing job. When i run the bash ./train_vae.sh NGPU=3(i have three gpus of 3090),the following problem orrcued: 
    Traceback (most recent call last):
  File "/home/whc/miniconda3/envs/lion_env/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/whc/miniconda3/envs/lion_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/whc/LION/utils/utils.py", line 1155, in init_processes
    torch.cuda.set_device(args.local_rank)
  File "/home/whc/miniconda3/envs/lion_env/lib/python3.8/site-packages/torch/cuda/__init__.py", line 311, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Looking for your enswer. Thanks!

**Comment by Wanghc233** [comment]
i use rtx3090,i input "export TORCH_CUDA_ARCH_LIST="8.0"can slove this "nvcc fatal : Unsupported gpu architecture 'compute_86'" problem.

**Comment by Wanghc233** [comment]
终端输一次就行，不用改全局环境，不然你的其他代码可能运行不了，先在终端输入export TORCH_CUDA_ARCH_LIST="8.0"回车后在输入python train.py

**Comment by Philcalab** [comment]
> 终端输一次就行，不用改全局环境，不然你的其他代码可能运行不了，先在终端输入export TORCH_CUDA_ARCH_LIST="8.0"回车后在输入python train.py

我的还是不行，报Using /home/user/.cache/torch_extensions/py38_cu111 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/user/.cache/torch_extensions/py38_cu111/emd_ext/build.ninja...
Building extension module emd_ext...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /usr/local/cuda:/bin/nvcc  -DTORCH_EXTENSION_NAME=emd_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/include -isystem /home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/include/TH -isystem /home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda:/include -isystem /home/user/anaconda3/envs/lion_env/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -std=c++14 -c /media/user/lc/LC/Upsampling/LION/LION-main/third_party/PyTorchEMD/cuda/emd_kernel.cu -o emd_kernel.cuda.o 
FAILED: emd_kernel.cuda.o 
/usr/local/cuda:/bin/nvcc  -DTORCH_EXTENSION_NAME=emd_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/include -isystem /home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/include/TH -isystem /home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda:/include -isystem /home/user/anaconda3/envs/lion_env/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -std=c++14 -c /media/user/lc/LC/Upsampling/LION/LION-main/third_party/PyTorchEMD/cuda/emd_kernel.cu -o emd_kernel.cuda.o 
/bin/sh: 1: /usr/local/cuda:/bin/nvcc: not found
[2/3] c++ -MMD -MF emd.o.d -DTORCH_EXTENSION_NAME=emd_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/include -isystem /home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/include/TH -isystem /home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda:/include -isystem /home/user/anaconda3/envs/lion_env/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -std=c++17 -c /media/user/lc/LC/Upsampling/LION/LION-main/third_party/PyTorchEMD/cuda/emd.cpp -o emd.o 
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1717, in _run_ninja_build    subprocess.run(
  File "/home/user/anaconda3/envs/lion_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "demo.py", line 17, in <module>
    from models.lion import LION
  File "/media/user/lc/LC/Upsampling/LION/LION-main/models/lion.py", line 8, in <module>
    from models.vae_adain import Model as VAE
  File "/media/user/lc/LC/Upsampling/LION/LION-main/models/vae_adain.py", line 14, in <module>
    from utils.model_helper import import_model 
  File "/media/user/lc/LC/Upsampling/LION/LION-main/utils/model_helper.py", line 14, in <module>
    from utils.evaluation_metrics_fast import distChamferCUDA, emd_approx, distChamferCUDA_l1
  File "/media/user/lc/LC/Upsampling/LION/LION-main/utils/evaluation_metrics_fast.py", line 24, in <module>
    from third_party.PyTorchEMD.emd_nograd import earth_mover_distance_nograd
  File "/media/user/lc/LC/Upsampling/LION/LION-main/third_party/PyTorchEMD/emd_nograd.py", line 4, in <module>
    from third_party.PyTorchEMD.backend import emd_cuda_dynamic as emd_cuda 
  File "/media/user/lc/LC/Upsampling/LION/LION-main/third_party/PyTorchEMD/backend.py", line 10, in <module>
    emd_cuda_dynamic = load(name='emd_ext',
  File "/home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1337, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1449, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/user/anaconda3/envs/lion_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'emd_ext'

**Comment by Philcalab** [comment]
> 终端输一次就行，不用改全局环境，不然你的其他代码可能运行不了，先在终端输入export TORCH_CUDA_ARCH_LIST="8.0"回车后在输入python train.py

现在只能在终端才能跑通，在pycharm里面Run就报错
